### PR TITLE
allow users to star packages with an auth token

### PR DESCRIPTION
**Pull request by bcoe**
Let a user star with their auth-token, important for registry-2.0.

### CODE REVIEW

**Comment by othiym23** [comment]
Squashed and some mild stylistic tweaks made before merging to master.

**Comment by oncletom** [comment]
Which means we could do eventually `npm star @myorg/mypackage --registry=https://<token>@my.registry.example.com`? :-)

**Comment by bcoe** [comment]
@oncletom that should work, although I believe we have some of the listing endpoints currently locked down in npm Enterprise.

I know that stars are likely one of the most sought after features for the Enterprise, so don't hesitate to open issues surrounding this feature ;)

**Comment by othiym23** [comment]
@oncletom Just a quick note: npm uses the credentials for a given scope when making requests, and for those credentials to be sent with `npm --registry` requests, you have to have logged into that registry using `npm login --scope --registry` so that the necessary configuration information can be set up in your `.npmrc`. Just putting the token in the URL is probably never going to work with npm.

**Pull request merged**
