### PR TITLE
using clone because JSON.parse(JSON.stringify(...)) errors when given undefined

### PR DESCRIPTION
**Pull request by antialias**

### CODE REVIEW

**Comment by antialias** [comment]
bump

**Comment by antialias** [comment]
Need anything else from me on this before it can be reviewed?

**Comment by antialias** [comment]
bump

**Comment by antialias** [comment]
bump. What would like me to do with the PR? Say the word and I'll stop you guys about it.

**Comment by antialias** [comment]
(edited comment on github)

**Comment by antialias** [comment]
bump @othiym23 @iarna

**Comment by necccc** [comment]
+1
This would just solve a weird issue for us right now, the `root.maintainers` field seems to undefined in some cases, and prevents publishing

**Comment by antialias** [comment]
bump

**Comment by antialias** [comment]
bump @othiym23 @iarna

**Comment by antialias** [comment]
bump @othiym23 @iarna

**Comment by zkat** [comment]
ugh this has been sitting around forever. We really shouldn't leave things hanging for this long like this.

Unfortunately, I would not take this patch: I don't think it's necessary to drag in a whole new dependency, when you can easily guard in this case with `var maint = root.maintainers && JSON.parse(JSON.stringify(root.maintainers))`

So I'm gonna close this, but I'll take a patch for a version using the guard? That seems fine enough to me.

**Comment by antialias** [comment]
@zkat https://github.com/npm/npm-registry-client/pull/171

**Pull request closed without merging**
