### PR TITLE
Updated ping command

### PR DESCRIPTION
**Pull request by zkat**
I've taken @michaelnisi's PR ( #55 ) and brought it up to date -- it was sitting around for a while and it kinda bitrotted a bit. The `/-/ping` endpoint is available on the registry now, so I think we can land this safely. /cc @iarna @othiym23

### CODE REVIEW

**Comment by michaelnisi** [comment]
Thanks @zkat.

**Comment by zkat** [comment]
No problem! It should pop up in this week's release (on both `npm@2` and `npm@3`) Cheers, and thanks for the initial code! :) (now just gotta get this thing reviewed...)

**Comment by iarna** [comment]
🐑

**Comment by zkat** [comment]
Merged as of 177d37a0

Should go into this week's release!

**Pull request closed without merging**
