### PR TITLE
add data and response into request

### PR DESCRIPTION
**Pull request by watilde**
from https://github.com/npm/npm/issues/15306. To get a statusCode in `npm/lib/ping.js`, we need to pass them even error exists.

### CODE REVIEW

**Comment by watilde** [comment]
@zkat Hello! I just added a test for it now :)

**Comment by zkat** [comment]
@watilde thanks! Could you make sure `data` and `response` are part of the tests, too? This was helpful, thank you ❤️

**Comment by watilde** [comment]
Ah you're right, that should be checked in tests :)

I've added the following two lines for it!
```diff
+    t.same(data, JSON.stringify(wanted))
+    t.same(res.body.toString(), JSON.stringify(wanted))
```

**Comment by zkat** [comment]
Released as `npm-registry-client@7.5.0`

**Comment by watilde** [comment]
Great! Arigato<3

**Comment by zkat** [comment]
いいえいいえ。こちらこそ、ワチくん。＾＿＿＿＾

**Pull request merged**
